### ISSUE TITLE
Reboot automatically after CARROOT displayed.

### ISSUE THREAD

**Issue by usouta** [DavidBuchanan314/rabbit_r1_boot_notes#1]
I tried it in the environment at hand.

> If it works, you should see log messages all the way up to [+] It worked???!?, and the device will start booting normally.

>During boot, you should see a "BOOTING CARROOT" message appear in a very tiny font at the bottom of the screen, along with some ASCII art.

After paddling to this point, the device automatically rebooted and no further processing could be carried out.
Is this the correct behaviour?

OS : Monterey
Intel Mac

**Comment by DavidBuchanan314** [comment]
That sounds unexpected.

Check the youtube demo if you'd like to make extra sure what it's supposed to look like when it works: https://www.youtube.com/watch?v=WFj9VPzNgn4

What firmware version is your R1 running? Have you used any other rooting/jailbreaking tools on it before now? (e.g. https://github.com/RabbitHoleEscapeR1/r1_escape )

**Comment by usouta** [comment]
I was wrong, CARROOT is functioning as per the youtube video. I respect and thank you for your excellent work.
This rooting is working inside the device, so fastboot and adb cannot be used, right? Can I use it for FLASHing system.img?

**Comment by DavidBuchanan314** [comment]
You don't need this for flashing a system.img, you can just use mtkclient for that, see https://github.com/RabbitHoleEscapeR1/r1_escape

The whole point of my tool is that it *doesn't* flash internal storage.

You can find instructions for enabling ADB in the docs https://github.com/DavidBuchanan314/rabbit_r1_boot_notes/tree/main/scripts/webusb

**Comment by usouta** [comment]
I understood the gist of the tool. 
I apologise for asking such a rudimentary question.
 Thank you for your sincere answer.
